#基础路径配置
base:
  base_spgl_url: https://api.weixin.qq.com
  base_wyxw_url: https://api.apiopen.top
  base_md5_url: http://127.0.0.1:5000
#日志配置
log:
  log_name: logs_
  log_level: info
  log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:%(lineno)d [%(levelname)s] %(message)s'